# This file was generated by GoReleaser. DO NOT EDIT.
cask "kamakiri" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "8b01622d3f7d2b90b63fd557dfc3609b457c57bb675a8f16db771344f5004b5d"
      url "https://github.com/kamakiri-labs/kamakiri/releases/download/v#{version}/kamakiri-darwin-arm64"
      binary "kamakiri-darwin-arm64", target: "kamakiri"
    end
    on_intel do
      sha256 "f6f3e4fc7c6fc3c756afa826041b0e74d48120da4088579c2790bea3b08cda1f"
      url "https://github.com/kamakiri-labs/kamakiri/releases/download/v#{version}/kamakiri-darwin-amd64"
      binary "kamakiri-darwin-amd64", target: "kamakiri"
    end
  end
  on_linux do
    on_arm do
      sha256 "073a18dd9c375b75570e95b36c99e43928cf2b5d8d5bc7eb04ea427fcf646050"
      url "https://github.com/kamakiri-labs/kamakiri/releases/download/v#{version}/kamakiri-linux-arm64"
      binary "kamakiri-linux-arm64", target: "kamakiri"
    end
    on_intel do
      sha256 "0575b2227443a0a360925b37c782a373daccc88a9866e0c7397837ebc74c796c"
      url "https://github.com/kamakiri-labs/kamakiri/releases/download/v#{version}/kamakiri-linux-amd64"
      binary "kamakiri-linux-amd64", target: "kamakiri"
    end
  end

  name "kamakiri"
  desc "CLI for Kamakiri Pages"
  homepage "https://github.com/kamakiri-labs/kamakiri"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
