# This file was generated by GoReleaser. DO NOT EDIT.
cask "kamakiri" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "ab92a16fd28a94536e54b51fde1c9258c650af528a105daf71cd61698f8f3488"
      url "https://github.com/kamakiri-labs/kamakiri/releases/download/v#{version}/kamakiri-darwin-arm64"
      binary "kamakiri-darwin-arm64", target: "kamakiri"
    end
    on_intel do
      sha256 "02bf9b587362a9545c6a87654ed7668685282ee546e96a31d65e813dacd8be5c"
      url "https://github.com/kamakiri-labs/kamakiri/releases/download/v#{version}/kamakiri-darwin-amd64"
      binary "kamakiri-darwin-amd64", target: "kamakiri"
    end
  end
  on_linux do
    on_arm do
      sha256 "760092a12e651f2791c4f964ae4e8bf28243bf96deb16b7f84740d3bac639fca"
      url "https://github.com/kamakiri-labs/kamakiri/releases/download/v#{version}/kamakiri-linux-arm64"
      binary "kamakiri-linux-arm64", target: "kamakiri"
    end
    on_intel do
      sha256 "cd8c1883cebd102186eb2d196d742b3bf748e75be6698ff5c63a6377eb8ddeae"
      url "https://github.com/kamakiri-labs/kamakiri/releases/download/v#{version}/kamakiri-linux-amd64"
      binary "kamakiri-linux-amd64", target: "kamakiri"
    end
  end

  name "kamakiri"
  desc "CLI for Kamakiri Pages"
  homepage "https://github.com/kamakiri-labs/kamakiri"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
