# This file was generated by GoReleaser. DO NOT EDIT.
cask "kamakiri" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "8820b954c73c158f85347bffab37953d4efc8aeb523dfec0893f3c8c832fdc83"
      url "https://github.com/kamakiri-labs/kamakiri/releases/download/v#{version}/kamakiri-darwin-arm64"
      binary "kamakiri-darwin-arm64", target: "kamakiri"
    end
    on_intel do
      sha256 "962ba2a345ebcb97f74e4115dec5d115a9dfc8c3e4e8cbdeca5ec5f176bf2de0"
      url "https://github.com/kamakiri-labs/kamakiri/releases/download/v#{version}/kamakiri-darwin-amd64"
      binary "kamakiri-darwin-amd64", target: "kamakiri"
    end
  end
  on_linux do
    on_arm do
      sha256 "117b241e0df0b079f27198ffc7138af5fdca4341658b96d0a61d277eafb15d13"
      url "https://github.com/kamakiri-labs/kamakiri/releases/download/v#{version}/kamakiri-linux-arm64"
      binary "kamakiri-linux-arm64", target: "kamakiri"
    end
    on_intel do
      sha256 "2bd5ea9749dfc79d8865070047cefd0e72f9ccb885b322682f6a8aecea857c93"
      url "https://github.com/kamakiri-labs/kamakiri/releases/download/v#{version}/kamakiri-linux-amd64"
      binary "kamakiri-linux-amd64", target: "kamakiri"
    end
  end

  name "kamakiri"
  desc "CLI for Kamakiri Pages"
  homepage "https://github.com/kamakiri-labs/kamakiri"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
